package syeda;

public enum ProvinceTerr {

	NEWFOUNDLANDANDLABRADOR, NOVASCOTIA, PRINCEEDWARDISLAND, NEWBRUNSWICK, QUEBEC, ONTARIO,
		MANITOBA, SASKATCHEWAN, ALBERTA, BRITISHCOLUMBIA, YUKON, NORTHWESTTERRITORIES, NUNAVUT;
	
}
